Repository hmcts/ctsc-work-allocation, pull requests merged in 2020-07, with the labels that each got.

#205 Fix pr build
  Jenkinsfile_CNP
  build.gradle
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:ctsc, prd:ctsc, rel:ctsc-work-allocation-pr-205

#208 Use local merged tags
  infrastructure/main.tf
Labels: ns:ctsc, prd:ctsc, rel:ctsc-work-allocation-pr-208

#214 do not use variable for logging versions to see if dependabot can rec…
  build.gradle
Labels: ns:ctsc, prd:ctsc, rel:ctsc-work-allocation-pr-214

#225 Upgrade springfox
  README.md
  build.gradle
  src/main/java/uk/gov/hmcts/reform/workallocation/config/SwaggerConfiguration.java
Labels: ns:ctsc, prd:ctsc, rel:ctsc-work-allocation-pr-225

#226 spring boot, chart and missing gradlew updates
  build.gradle
  charts/ctsc-work-allocation/Chart.yaml
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: ns:ctsc, prd:ctsc, rel:ctsc-work-allocation-pr-226
