Repository hmcts/ctsc-work-allocation, pull requests merged in 2020-09, with the labels that each got.

#249 CTSCT-28: Fixing postgres jar upgrade
  src/main/resources/application.yaml
Labels: ns:ctsc, prd:ctsc, rel:ctsc-work-allocation-pr-249

#252 CTSCT-28: Fixing postgres jar upgrade
  src/main/resources/application.yaml
Labels: ns:ctsc, prd:ctsc, rel:ctsc-work-allocation-pr-252

#253 CTSCT-28: Fixing postgres jar upgrade
  build.gradle
  src/main/resources/application.yaml
Labels: ns:ctsc, prd:ctsc, rel:ctsc-work-allocation-pr-253

#259 Ctsct 28
  build.gradle
  charts/ctsc-work-allocation/Chart.yaml
  charts/ctsc-work-allocation/values.preview.template.yaml
  charts/ctsc-work-allocation/values.yaml
  src/main/resources/application.yaml
Labels: ns:ctsc, prd:ctsc, rel:ctsc-work-allocation-pr-259

#268 CTSCT-48 Bump org.owasp.dependencycheck from 5.3.2.1 to 6.0.0
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ctsc, prd:ctsc, rel:ctsc-work-allocation-pr-268

#276 Revert: Bump applicationinsights-logging-logback from 2.6.1 to 2.6.2 …
  build.gradle
Labels: ns:ctsc, prd:ctsc, rel:ctsc-work-allocation-pr-276

#277 CTSCT-60 Add/Upgrade terraform version 0.13.3
  charts/ctsc-work-allocation/Chart.yaml
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:ctsc, prd:ctsc, rel:ctsc-work-allocation-pr-277
